### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by mp4096** [tum-rt/web-quiz#4]
Due to the Travis build failures: Do you think it is necessary to target Node 4, 5 and 6? I think we can allow us the luxury to target only the newest stable version.

OTOH: What is the state of Node right now, what is the adoption of Node 6? Do we exclude a lot of installs if we do not support Node 4?

**Comment by syxolk** [comment]
There should be no reason to NOT upgrade to the latest Node version since the Node API is pretty much stable by now. The build problems were mainly caused by usage of pretty new JavaScript functions and syntax.

We should always support the latest LTS version, which is currently 6.x. On the other hand there is no particular reason to not support 4.x onwards.

**Comment by syxolk** [comment]
Ok, `const` is totally broken in 4.x

**Comment by mp4096** [comment]
Hehe. Then, as a halfway BDFTTB (for the time being) I declare support for Node 4 and 5 dropped. Please use the latest JS/Node features if they make the code safer and/or more maintainable.

@syxolk Todo before closing this issue:
- [ ] update README.md to `Node >= 6.x`
- [ ] remove older versions from the Travis config

**Comment by syxolk** [comment]
Everything seems to work now on 4.x with commit 82820545c3bb5188caa804d4ba1fe8065752a7fd

I just added some test scripts for the old versions as well.

**Comment by mp4096** [comment]
Yep, I've seen that the builds went green. I still suggest we focus on `6.x`, maintaining several versions is a PITA _(uhm, did someone say Python?..)_

Or we could leave older versions in Travis but allow the builds to fail:
```yaml

matrix:
  allow_failures:
    - node_js: "4"
    - node_js: "5"
```
